export type AbilityKey = "strength" | "dexterity" | "constitution" | "intelligence" | "wisdom" | "charisma";
export type HitDieSize = 6 | 8 | 10 | 12;
export type CasterKind = "NONE" | "FULL" | "HALF" | "THIRD" | "PACT";
export type ClassLevelEntry = { classKey: string; level: number; subclassKey?: string | null; isPrimary?: boolean };
export type AbilityRequirement = { ability: AbilityKey; minimum: number };
export type ClassRule = {
  key: string;
  labels: { it: string; en: string };
  aliases: readonly string[];
  hitDie?: HitDieSize;
  primaryAbilities: readonly AbilityKey[];
  multiclassPrerequisites: { anyOf: readonly (readonly AbilityRequirement[])[] };
  casterKind?: CasterKind;
  subclassLevel?: number;
  source: { rulesetId: string; version: string };
};
export type SubclassRule = {
  key: string;
  classKey: string;
  labels: { it: string; en: string };
  aliases: readonly string[];
  casterKind?: CasterKind;
  source: { rulesetId: string; version: string };
};
export const CHARACTER_RULESET: Readonly<{ id: string; version: string; source: string }>;
export const ABILITY_KEYS: readonly AbilityKey[];
export const HIT_DIE_SIZES: readonly HitDieSize[];
export const CASTER_KINDS: readonly CasterKind[];
export const CLASS_RULES: Readonly<Record<string, ClassRule>>;
export const SUBCLASS_RULES: Readonly<Record<string, SubclassRule>>;
export function normalizeClassKey(value: unknown, rules?: Record<string, ClassRule> | ClassRule[]): string | null;
export function normalizeSubclassKey(value: unknown, rules?: Record<string, SubclassRule> | SubclassRule[]): string | null;
export function getClassRule(value: unknown, rules?: Record<string, ClassRule> | ClassRule[]): ClassRule | null;
export function getSubclassRule(value: unknown, rules?: Record<string, SubclassRule> | SubclassRule[]): SubclassRule | null;
export function resolveCharacterLevel(entries: ClassLevelEntry[]): number;
export function resolveClassLevel(entries: ClassLevelEntry[], classKey: string, classRules?: Record<string, ClassRule> | ClassRule[]): number;
export function resolveProficiencyBonus(levelOrEntries: number | ClassLevelEntry[]): number;
export function resolveHitDicePools(entries: ClassLevelEntry[], classRules?: Record<string, ClassRule> | ClassRule[]): { pools: Record<`d${HitDieSize}`, number>; unresolvedClassKeys: string[] };
export function resolveEffectiveCasterLevel(entries: ClassLevelEntry[], options?: { classRules?: Record<string, ClassRule> | ClassRule[]; subclassRules?: Record<string, SubclassRule> | SubclassRule[] }): { level: number; unresolvedClassKeys: string[] };
export function resolvePactMagicLevel(entries: ClassLevelEntry[], classRules?: Record<string, ClassRule> | ClassRule[]): { level: number; unresolvedClassKeys: string[] };
export function resolveSubclassEligibility(entry: ClassLevelEntry, options?: { classRules?: Record<string, ClassRule> | ClassRule[]; subclassRules?: Record<string, SubclassRule> | SubclassRule[] }): { status: "MANUAL" | "INVALID" | "ELIGIBLE" | "NOT_YET_ELIGIBLE"; eligible: boolean; requiredLevel: number | null; reason: string | null };
export function evaluateMulticlassPrerequisites(currentEntries: ClassLevelEntry[], targetClassKey: string, abilityScores: Partial<Record<AbilityKey, number>>, classRules?: Record<string, ClassRule> | ClassRule[]): { status: "MANUAL" | "ELIGIBLE" | "INELIGIBLE"; eligible: boolean; failedClassKeys: string[]; reason: string | null };
export function resolveProgressionSummary(entries: ClassLevelEntry[], options?: { classRules?: Record<string, ClassRule> | ClassRule[]; subclassRules?: Record<string, SubclassRule> | SubclassRule[] }): { characterLevel: number; proficiencyBonus: number; hitDicePools: Record<`d${HitDieSize}`, number>; effectiveCasterLevel: number; pactMagicLevel: number; unresolvedClassKeys: string[] };
